# Generated by Django 4.0.1 on 2022-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_restabts_restprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restprofile',
            name='about',
            field=models.TextField(max_length=100),
        ),
    ]
