# Generated by Django 4.0.1 on 2022-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_restprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restprofile',
            name='about',
            field=models.CharField(max_length=100),
        ),
    ]
