# Generated by Django 4.0.1 on 2022-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_restaurant_status_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='restprofile',
            name='map',
            field=models.URLField(default=''),
        ),
    ]
