# Generated by Django 4.0.1 on 2022-05-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_table_contactno_alter_table_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='rest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.restaurant'),
            preserve_default=False,
        ),
    ]
