# Generated by Django 4.0.1 on 2022-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_table_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restprofile',
            name='about',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restprofile',
            name='directions',
            field=models.CharField(max_length=1000),
        ),
    ]
