# Generated by Django 4.0.1 on 2022-05-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_feedback_processed_on_feedback_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.restaurant'),
        ),
    ]
